Transform: AWS::Serverless-2016-10-31
Resources:

  MyFunction:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: makefile
    Properties:
      Runtime: provided.al2
      CodeUri: ./my-function
      Handler: bootstrap

  MyFunctionLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub /my/stack/lambda/${MyFunction}
      RetentionInDays: 7

Outputs:
  FunctionName:
    Description: Created Function Name
    Value:  !Ref MyFunction
    Export:
      Name: !Join [ ":", [ !Ref "AWS::StackName", FunctionName ] ]
